name: Run tests, build docker image and run docker compose on production

on:
  push:
    branches:
      - "main"

jobs:
  
  backend-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.0'
    - name: Install dependences
      run: npm install
    - name: Execute tests
      run: npm run test
  
  build:
    needs: backend-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/msd-express-mongo:latest
  integration:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - name: SSH Command
         uses: D3rHase/ssh-command-action@v0.2.2
         with:
          host:  ${{ secrets.IP_DROPLET }}
          user: developer
          private_key:  ${{ secrets.SSH_PRIVATE_KEY }}
          #command to be executed in droplet
          command: echo ${{ secrets.DEVELOPER_PASS }} | sudo -S docker compose down && echo ${{ secrets.DEVELOPER_PASS }} | sudo -S docker compose pull && echo ${{ secrets.DEVELOPER_PASS }} | sudo -S docker compose up -d && echo ${{ secrets.DEVELOPER_PASS }} | sudo -S docker image prune -f
